# Generated by Django 2.2 on 2019-04-30 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookreviewapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='point',
            field=models.IntegerField(choices=[(1, '♥'), (2, '♥♥'), (3, '♥♥♥'), (4, '♥♥♥♥'), (5, '♥♥♥♥♥')], default=3),
        ),
    ]
