# Generated by Django 2.2 on 2019-04-30 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookreviewapp', '0002_auto_20190430_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contents',
            new_name='content',
        ),
    ]
