# Generated by Django 2.2.1 on 2019-05-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreviewapp', '0006_auto_20190430_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
